# Generated by Django 5.2.9 on 2025-12-13 08:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(help_text='Skills and qualifications (comma-separated or free text)')),
                ('availability', models.JSONField(default=dict, help_text='Availability schedule (JSON format: days/times)')),
                ('interests', models.TextField(help_text='Interests and preferences (comma-separated or free text)')),
                ('max_hours_per_week', models.IntegerField(default=10, help_text='Maximum hours per week the volunteer can commit', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_logged', models.DecimalField(decimal_places=2, help_text='Hours logged', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField(help_text='Date of participation')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the participation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(help_text='Opportunity for which hours were logged', on_delete=django.db.models.deletion.CASCADE, related_name='participation_records', to='opportunities.opportunity')),
                ('volunteer', models.ForeignKey(help_text='Volunteer who logged the hours', on_delete=django.db.models.deletion.CASCADE, related_name='participation_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['volunteer'], name='volunteers__volunte_98af80_idx'), models.Index(fields=['opportunity'], name='volunteers__opportu_ecfc1b_idx'), models.Index(fields=['date'], name='volunteers__date_c325de_idx')],
            },
        ),
    ]
