# Generated by Django 5.2.9 on 2025-12-13 08:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Opportunity title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the opportunity')),
                ('location', models.CharField(help_text='Location of the opportunity', max_length=200)),
                ('category', models.CharField(choices=[('EDUCATION', 'Education'), ('HEALTHCARE', 'Healthcare'), ('ENVIRONMENT', 'Environment'), ('COMMUNITY', 'Community Service'), ('ANIMALS', 'Animals'), ('ARTS', 'Arts & Culture'), ('SPORTS', 'Sports & Recreation'), ('TECHNOLOGY', 'Technology'), ('OTHER', 'Other')], default='OTHER', help_text='Category of the opportunity', max_length=20)),
                ('required_skills', models.TextField(help_text='Required skills (comma-separated or free text)')),
                ('min_hours_per_week', models.IntegerField(help_text='Minimum hours per week required', validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField(help_text='Start date of the opportunity')),
                ('end_date', models.DateField(help_text='End date of the opportunity')),
                ('is_remote', models.BooleanField(default=False, help_text='Whether this is a remote opportunity')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', help_text='Current status of the opportunity', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(help_text='Organisation posting this opportunity', on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='organisations.organisation')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', help_text='Application status', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.ForeignKey(help_text='Volunteer applying', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(help_text='Opportunity being applied to', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status'], name='opportuniti_status_fb4df4_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['category'], name='opportuniti_categor_dd0690_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['location'], name='opportuniti_locatio_df5b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['organisation'], name='opportuniti_organis_d1d7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['start_date', 'end_date'], name='opportuniti_start_d_815147_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='opportuniti_status_a74b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['volunteer'], name='opportuniti_volunte_149df9_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['opportunity'], name='opportuniti_opportu_26a9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='opportuniti_created_01a555_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('volunteer', 'opportunity')},
        ),
    ]
