# Generated by Django 5.2.9 on 2025-12-13 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organisation name', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the organisation')),
                ('contact_email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Organisation website URL', null=True)),
                ('verified', models.BooleanField(default=False, help_text='Whether the organisation has been verified by staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(help_text='Organisation administrator user', on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['verified'], name='organisatio_verifie_1fbf31_idx'), models.Index(fields=['admin'], name='organisatio_admin_i_54f262_idx')],
            },
        ),
    ]
